# Generated by Django 5.2.7 on 2025-10-31 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_type', models.CharField(choices=[('summary', 'Summary'), ('detailed', 'Detailed'), ('custom', 'Custom')], default='summary', max_length=50)),
                ('total_sessions_started', models.PositiveIntegerField(default=0)),
                ('total_sessions_submitted', models.PositiveIntegerField(default=0)),
                ('response_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('total_answers', models.BigIntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='form.process')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
