# Generated by Django 5.2.7 on 2025-11-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='participants_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='response_rate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_answers',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_sessions_started',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_sessions_submitted',
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
