# Generated by Django 5.2.7 on 2025-10-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='access_password_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='process',
            name='access_password_hash',
            field=models.CharField(max_length=128),
        ),
    ]
