# Generated by Django 5.2.7 on 2025-10-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order_index',
        ),
    ]
